name: AplageSentinellesEnv
channels:
  - defaut
dependencies:
  # required
  - pip
  - tqdm
  - zipfile
  - numpy>=1.21.5
  - matplotlib>=3.2.2
  - geopandas>=0.10.2
  - pandas>=1.3.5
  - xarray>=0.18.2
  - GDAL>=3.0.4   # pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`
  - scipy>=1.8.0  # cannot read or write netCDF files without scipy installed
  - rasterio

  # code check
  - black>=7.1.2

  # web
  - markdown
  - pyyaml

  # testing
  - pre-commit>=2.18.1
  - pytest>=3.7
  - black>=7.1.2
